if: |
  commit_message =~ /^Build.*:/

os: linux

dist: xenial

language: shell

git:
  depth: 2

services:
  - docker

env:
  global:
    - DOCKER_ORG=provarepro
    - DOCKER_USER=reprova
    # DOCKER_PASS="..."
    - secure: "zqLusYkToR3/ye1uSSfpX75yBV4DSLyam+emO299VXELv/6dErt+vYd0m/S+wxct5CUrkPeDFt+PEVVCQ7rqwki1ompa7ZtV3cOfv5MGyQKLFhlQUezpADDwNN3ks4spaQ/K3OoaL9apNi1K6Gc1PyFH2soUwnRuxevchGfUF4xqIoxrgjvkpB3yGxIpLbu/sB0MyjD48MvCINIpJaXHEQ0SYt6OzV28TEOxLlIA+YZ1rArHSk0as0iGpJXjlCjI5dKQHDQ+J4iiqHY1QPih+G2bdYgaA0AMbYR6Py/HnMTaz/Bm7tAIEV3r7N6RjKRc24Ajo+4AD3dmuwN7/GvW7dprX2iSrkqW/I9PAR5nWRbw0gHWKEda3eS2GT81ErDoZsiCXF/EC5koLirhojTEZPB0izYyiz0rQ+z/tWx/SHUc9HUmDDHRwk7jQkquhZ8M/P+yfSe2BRPQuBROgLNwItsnLexiRhgDhtDYWFGmhQxy6tP8oO1SVnSdK/FrxSH5z/BDKDR5CCBzQY2SVwQkDTfeaEl4ibf2iovoEJitSDxrdtRb1qpIbyg7XjVGAdm6HyVHdrlQt2Orm5uGcwB4RGPPF0icfcJ9Pp+DJ+QWQUsyHPZsNt4B8ibqVXuuT8pLUxHPao69BnTsynIdd6mAM7/zW3xVsYE1tZlVMXqbpeo="

jobs:
  include:
    - stage: build docker image
      if: |
        commit_message =~ /^Build docker:*/
      script: |
        SW_NAME=`echo ${TRAVIS_REPO_SLUG##*/} | sed 's/ *$//g'`
        DOCKER_SW_NAME=${SW_NAME,,}
        SW_TAG=${TRAVIS_COMMIT_MESSAGE#*"Build docker:"}
        SW_TAG=`echo ${SW_TAG%%,*} | sed 's/ *$//g'`
        DOCKERFILEPATH=$(find . -name "${SW_TAG}.dockerfile")

        IMAGE_NAME="${DOCKER_ORG}/${DOCKER_SW_NAME}:${SW_TAG}"

        docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

        docker pull ${IMAGE_NAME} || true

        cd ${DOCKERFILEPATH}

        docker build\
          --label "BUILT-BY=Travis"\
          --label "BUILT-FROM=${TRAVIS_REPO_SLUG}"\
          --label "BUILD-LOG=${TRAVIS_BUILD_WEB_URL}"\
          --tag ${IMAGE_NAME}\
          -f ./${SW_TAG}.dockerfile\
          .

        docker images

        docker push ${IMAGE_NAME}
